# Generated by Django 4.2.10 on 2024-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_order_shippingaddress_review_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d"
            ),
        ),
    ]
